local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file)
vim.keymap.set("n", "m", ui.toggle_quick_menu)
-- vim.keymap.set("n", "m", "<cmd>lua require('telescope').extensions.harpoon.marks(require('telescope.themes').get_dropdown{previewer = false, initial_mode='normal', prompt_title='Harpoon'})<cr>")

vim.keymap.set("n", "<C-s>", function() ui.nav_file(1) end)
vim.keymap.set("n", "<C-w>", function() ui.nav_file(2) end)
vim.keymap.set("n", "<C-e>", function() ui.nav_file(3) end)
vim.keymap.set("n", "<C-b>", function() ui.nav_file(4) end)
vim.keymap.set("n", "<C-n>", function() ui.nav_file(5) end)
vim.keymap.set("n", "<C-m>", function() ui.nav_file(6) end)
vim.keymap.set("n", "<C-;>", function() ui.nav_file(7) end)
vim.keymap.set("n", "<C-'>", function() ui.nav_file(8) end)
vim.keymap.set("n", "<C-,>", function() ui.nav_file(9) end)
vim.keymap.set("n", "<C-.>", function() ui.nav_file(10) end)
