local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file)
vim.keymap.set("n", "m", ui.toggle_quick_menu)
-- vim.keymap.set("n", "m", "<cmd>lua require('telescope').extensions.harpoon.marks(require('telescope.themes').get_dropdown{previewer = false, initial_mode='normal', prompt_title='Harpoon'})<cr>")

vim.keymap.set("n", "<M-a>", function() ui.nav_file(1) end)
vim.keymap.set("n", "<M-s>", function() ui.nav_file(2) end)
vim.keymap.set("n", "<M-w>", function() ui.nav_file(3) end)
vim.keymap.set("n", "<M-e>", function() ui.nav_file(4) end)
vim.keymap.set("n", "<M-x>", function() ui.nav_file(5) end)
vim.keymap.set("n", "<M-x>", function() ui.nav_file(6) end)
-- vim.keymap.set("n", "<C-j>", function() ui.nav_file(7) end)
-- vim.keymap.set("n", "<C-k>", function() ui.nav_file(8) end)
-- vim.keymap.set("n", "<C-l>", function() ui.nav_file(9) end)
vim.keymap.set("n", "<M-n>", function() ui.nav_file(10) end)
